version: '3'

services:
  verify_payment_receipt:
    build: .
    container_name: verify_payment_receipt
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
